// ============================================================
// AI ADVISOR API ROUTE
// Server-side only. Receives a structured EstimatePacket context.
// The AI NEVER invents pricing — it only interprets the provided data.
// Requires OPENAI_API_KEY in .env.local
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import type { AIAdvisorContext, EstimateNarrative } from '@/types';
import { loadProcessedKnowledgeEntries } from '@/lib/processedIntelAdapter';

const SYSTEM_PROMPT = `You are an expert commercial glazing estimating advisor for the DMV (Washington DC, Maryland, Virginia) market.

You have access to the full Basis of Estimate narrative generated by the deterministic engine, including all source citations. Your role is to:
- Provide clear, professional commentary that DEFENDS and EXPLAINS the estimate
- Reference specific cited sources by name when explaining cost decisions (e.g., "per RSMeans 2024", "per DMV bid data")
- Answer "why is this number what it is?" for each major cost component
- Identify what the estimator should verify before final bid
- Explain the significance of risk flags in plain contractor language

CRITICAL RULES:
1. You NEVER invent, suggest, or imply specific dollar values or $/SF rates beyond what is explicitly provided in the estimate data
2. You NEVER override the deterministic calculation results
3. You ONLY interpret and explain the structured data you receive — cite it, don't change it
4. When defending a number, reference the actual source (RSMeans, DMV bid data, BLS PPI, etc.)
5. Keep your response practical, contractor-focused, and under 450 words
6. Use plain professional language — not academic or marketing language
7. Be direct about risks — do not sugarcoat critical flags`;

function buildUserPrompt(
  ctx: AIAdvisorContext,
  narrative?: EstimateNarrative,
  processedIntelContext?: string
): string {
  const narrativeSections = narrative?.sections.slice(0, 5).map(s =>
    `### ${s.heading}\n${s.body.slice(0, 400)}${s.body.length > 400 ? '...' : ''}`
  ).join('\n\n') ?? '';

  const citationList = narrative?.all_citations.map((c, i) =>
    `[${i + 1}] ${c.title} — ${c.publisher} (${c.source_type})`
  ).join('\n') ?? '';

  const liveDataNote = narrative?.live_data_applied
    ? `\nLIVE DATA APPLIED: ${narrative.live_data_note}`
    : '\nLIVE DATA: RSMeans 2024 baseline only (no live calibration active)';

  const procIntelBlock = processedIntelContext
    ? `\nLOCALLY INGESTED PROCUREMENT INTELLIGENCE (from firm's own bid file):\n${processedIntelContext}`
    : '';

  return `Please provide citation-backed advisory commentary defending and explaining this estimate:

ESTIMATE SUMMARY:
- System: ${ctx.work_type_name}
- Region: ${ctx.region_name}
- Project Type: ${ctx.project_type_label}
- Quantity: ${ctx.total_sf.toLocaleString()} SF
- Total Contract Value: $${ctx.grand_total.toLocaleString()}
- Effective Rate: $${ctx.effective_per_sf}/SF
- Market Position: ${ctx.market_position}
- Benchmark Range: $${ctx.benchmark_range.low}–$${ctx.benchmark_range.high}/SF (mid: $${ctx.benchmark_range.mid}/SF)
${liveDataNote}

CONFIDENCE: ${ctx.confidence_level} (${ctx.confidence_score}/100)
${ctx.confidence_factors.slice(0, 5).join('\n')}

RISK FLAGS (${ctx.risk_flag_messages.length} total):
${ctx.risk_flag_messages.slice(0, 5).join('\n')}

SPECIAL REQUIREMENTS: ${ctx.special_requirements.length > 0 ? ctx.special_requirements.join(', ') : 'None'}

BASIS OF ESTIMATE NARRATIVE (deterministic engine output):
${narrativeSections}

CITED SOURCES FOR THIS ESTIMATE:
${citationList}
${procIntelBlock}

Provide 4 focused paragraphs:
1. MARKET DEFENSE — Defend the $/SF rate citing specific sources (RSMeans 2024, DMV bid data, BLS PPI if applicable, and firm's own bid data if available above)
2. RISK BRIEFING — Explain the top 2–3 risks in plain language with specific recommended actions before bid
3. CONFIDENCE RATIONALE — Explain what the score means for this specific project and what would improve it
4. BOTTOM LINE — One crisp, actionable verdict: is this ready to bid, needs refinement, or needs major verification?`;
}

export async function POST(req: NextRequest) {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      { error: 'OPENAI_API_KEY not configured. Add it to .env.local to enable AI advisory.' },
      { status: 503 }
    );
  }

  let context: AIAdvisorContext;
  let narrative: EstimateNarrative | undefined;
  try {
    const body = await req.json();
    context = body.context as AIAdvisorContext;
    narrative = body.narrative as EstimateNarrative | undefined;
    if (!context?.work_type_name || !context?.grand_total) {
      return NextResponse.json({ error: 'Invalid estimate context provided.' }, { status: 400 });
    }
  } catch {
    return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 });
  }

  // Load locally-ingested procurement intel (server-side filesystem read)
  let processedIntelContext: string | undefined;
  try {
    const entries = loadProcessedKnowledgeEntries({
      workTypeId: context.work_type_name?.toLowerCase().replace(/\s+/g, '_'),
      regionId: context.region_name?.toLowerCase().includes('virginia') ? 'nova'
        : context.region_name?.toLowerCase().includes('maryland') ? 'maryland'
        : context.region_name?.toLowerCase().includes('d.c') || context.region_name?.toLowerCase().includes('dc') ? 'dc'
        : undefined,
      maxEntries: 6,
    });
    if (entries.length > 0) {
      processedIntelContext = entries
        .slice(0, 6)
        .map(e => `• ${e.title}: ${e.body.slice(0, 200)}`)
        .join('\n');
    }
  } catch {
    // Processed intel is optional — don't fail the request if files aren't there yet
  }

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: buildUserPrompt(context, narrative, processedIntelContext) },
        ],
        max_tokens: 700,
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      return NextResponse.json({ error: `OpenAI error: ${err}` }, { status: 502 });
    }

    const data = await response.json();
    const commentary = data.choices?.[0]?.message?.content ?? 'No commentary generated.';

    return NextResponse.json({ commentary });
  } catch (err) {
    return NextResponse.json(
      { error: `Request failed: ${err instanceof Error ? err.message : 'Unknown error'}` },
      { status: 500 }
    );
  }
}
